[versions]
slf4j = "2.0.17"
otel = "1.39.0"
junit = "5.10.2"
junit-platform = "1.10.2"
picocli = "4.7.5"
okhttp = "4.12.0"
javalin = "6.7.0"
guice = "7.0.0"
logback = "1.5.32"
jackson = "2.17.2"
mockito = "5.14.2"
spotless = "6.25.0"
shadow = "9.3.0"
sqlite = "3.47.2.0"
liquibase = "4.31.1"
guava = "33.2.1-jre"
grpc = "1.74.0"
protobuf = "3.25.3"
otel-proto = "1.9.0-alpha"

[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

otel-api = { group = "io.opentelemetry", name = "opentelemetry-api", version.ref = "otel" }
otel-sdk = { group = "io.opentelemetry", name = "opentelemetry-sdk", version.ref = "otel" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
picocli-codegen = { group = "info.picocli", name = "picocli-codegen", version.ref = "picocli" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
grpc-netty-shaded = { group = "io.grpc", name = "grpc-netty-shaded", version.ref = "grpc" }
grpc-services = { group = "io.grpc", name = "grpc-services", version.ref = "grpc" }
grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpc" }
grpc-util = { group = "io.grpc", name = "grpc-util", version.ref = "grpc" }
grpc-stub = { group = "io.grpc", name = "grpc-stub", version.ref = "grpc" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf" }
javax-annotation-api = { group = "javax.annotation", name = "javax.annotation-api", version = "1.3.2" }
opentelemetry-proto = { group = "io.opentelemetry.proto", name = "opentelemetry-proto", version.ref = "otel-proto" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
